[build.environment]
  NODE_VERSION = "18.18.0"


[build]
  functions = "functions"
  publish = "build"
  command = "npm run build"
  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

